//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Researches = new HashSet<Research>();
        }
    
        public int id { get; set; }
        [DisplayName("Họ và Tên")]
        [Required(ErrorMessage = "Họ và tên chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]
        public string Name { get; set; }
        [DisplayName("Quyền")]
        public string Role { get; set; }
        public string Check_active { get; set; }
        public string ms_id { get; set; }
        public int Falcuty_id { get; set; }
        [DisplayName("Mail Văn Lang")]
        [Required(ErrorMessage = "Mail chưa được nhập")]
        public string Email { get; set; }
        [DisplayName("Chức danh giảng dạy")]
        [Required(ErrorMessage = "Chức danh chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]
        public string Teaching_Name { get; set; }
        [DisplayName("Mã GV")]
        [Required(ErrorMessage = "Mã GV chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]
        public string Lecture_Code { get; set; }
        [DisplayName("Trình độ chuyên môn")]
        [Required(ErrorMessage = "Trình độ chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]
        public string Degree { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Research> Researches { get; set; }
    }
}
