//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    using System;
    using System.Collections.Generic;

    public partial class RearchItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RearchItem()
        {
            this.Researches = new HashSet<Research>();
        }
    
        public int id { get; set; }
        [DisplayName("Nội dung công việc")]
        [Required(ErrorMessage = "Nội dung công việc chưa được nhập")]
        [Remote("CTEx", "Item", ErrorMessage = "Nội dung đã tồn tại")]
        public string CT { get; set; }
        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "Đơn vị chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]

        public string unit { get; set; }
        [DisplayName("Quy đổi giờ chuẩn")]
        [Required(ErrorMessage = "Quy đổi giờ chuẩn chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]
        public Nullable<int> exchange { get; set; }
        [DisplayName("Ghi chú")]
        public string about { get; set; }
        [DisplayName("Danh Mục NCKH")]
        public int Category_id { get; set; }
        [DisplayName("Mã NCKH")]
        [Required(ErrorMessage = "Chưa nhập Mã NCKH")]
        [Remote("MaCT", "Item", ErrorMessage = "Mã NCKH đã tồn tại")]
        public string MaNCKH { get; set; }
    
        public virtual ResearchCategory ResearchCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Research> Researches { get; set; }
    }
}
