//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ResearchCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResearchCategory()
        {
            this.RearchItems = new HashSet<RearchItem>();
        }
    
        public int id { get; set; }
        [DisplayName("Danh mục NCKH")]
        [Required(ErrorMessage = "Chưa nhập tên danh mục NCKH")]
        [Remote("NameExists", "Category", ErrorMessage = "Tên danh mục đã tồn tại")]
        public string Name { get; set; }
        [DisplayName("Mã")]
        [Required(ErrorMessage = "Chưa nhập Mã")]
        [Remote("MaC", "Category", ErrorMessage = "Mã đã tồn tại")]
        public Nullable<int> Ma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RearchItem> RearchItems { get; set; }
    }
}
