//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Research
    {
        public int id { get; set; }
        [DisplayName("Diễn giải")]
        [Required(ErrorMessage = "Diễn giải chưa được nhập")]

        public string Explain { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "SL chưa được nhập")]
        public Nullable<int> Quantity { get; set; }
        [DisplayName("Ghi chú ")]
        public string Note { get; set; }
        public int Semester_id { get; set; }
        public int Item_id { get; set; }
        public int Account_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual RearchItem RearchItem { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
