//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    public partial class Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester()
        {
            this.Researches = new HashSet<Research>();
        }
    
        [Key]
        public int id_semester { get; set; }
        [DisplayName("Tên học kì")]
        [Remote("IsUserExists", "Semester", ErrorMessage = "Tên Học kì đã tồn tại")]
        [Required(ErrorMessage = "Tên học kì chưa được nhập")]
        [StringLength(50, ErrorMessage = "Không được quá 50 kí tự")]

        public string namesemester { get; set; }
        [DisplayName("Ngày bắt đầu")]
        [Required(ErrorMessage = "Ngày bắt đầu chưa được nhập")]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}")]
        [Column(TypeName = "date")]
        public DateTime? start_date { get; set; }
        [DisplayName("Ngày kết thúc")]
        [Required(ErrorMessage = "Ngày kết thức chưa được nhập")]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}")]
        [Column(TypeName = "date")]
        public Nullable<System.DateTime> end_date { get; set; }
        public int Account_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Research> Researches { get; set; }
    }
}
