//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_Danhmuc
    {
        public string Name { get; set; }
        public string namesemester { get; set; }
        public string Explain { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
        public int Semester_id { get; set; }
        public int Item_id { get; set; }
        public string HovaTen { get; set; }
        public string MaNCKH { get; set; }
        public string CT { get; set; }
        public string unit { get; set; }
        public Nullable<int> exchange { get; set; }
        public string about { get; set; }
    }
}
